### ISSUE TITLE
Get title song.

### ISSUE THREAD

**Issue by gitAdrianK** [akrimpenfort/pir-radiostation-analyser#1]
Trying around with hyper and grabbing a webpage does not grab the required field.

E.g.: For wdr the current song is shown in wdrrCurrentShowTitleTitle, grabbing the html and searching for wdrrCurrentShowTitleTitle gets not the current song but a song that has played minutes before, skipping some songs. It seems completely random when this field updates.

**Comment by gitAdrianK** [comment]
The wdrrCurrentShowTitleTitle given by hyper does not take javascript into account since it only grabs the html, the correct songname is inserted by js.

**Comment by gitAdrianK** [comment]
It seems the current song is being fetched from (for wdr) http://www.wdr.de/radio/radiotext/streamtitle_1live.txt?cb=53063601

Spez: It also seems to update instantly, it is a minimal html-file which makes parsing it even easier

**Comment by wimueller** [comment]
Sherlock was at work ;)

**Comment by gitAdrianK** [comment]
Now that I'm back from uni I could test if this can be grabbed with hyper, and it can.
Unless you have more smart comments 🤐  I'll close this issue and add these links to the wiki.
Most likely even get the first grabber for the radiostations on a dev branch.

**Comment by wimueller** [comment]
OK!
