### ISSUE TITLE
Collecting data?

### ISSUE THREAD

**Issue by wimueller** [akrimpenfort/pir-radiostation-analyser#15]
Are you already running the program to collect data, that we can show at the presentation. Or should I run it the over the next weeek?

**Comment by gitAdrianK** [comment]
2017-02-07T20:43:38+01:00 INFO: Start Analyzing Radio stations

**Comment by wimueller** [comment]
That means yes.

**Comment by gitAdrianK** [comment]
Ye, want a spoiler what radiostation repeats songs the most?

**Comment by wimueller** [comment]
Sure ;)

**Comment by gitAdrianK** [comment]
Antenne Charts, only 50 different songs played, and two songs already repeated 32 times
