### ISSUE TITLE
Präsentation

### ISSUE THREAD

**Issue by gitAdrianK** [akrimpenfort/pir-radiostation-analyser#16]
@wimueller ,wann hast du zeit mal das wir uns treffen und unsere präsentation erstellen?

**Comment by wimueller** [comment]
@akrimpenfort morgen noch eine Klausur dann habe ich Zeit. Schreib mir doch eine Mail, wann du Zeit hast.

**Comment by wimueller** [comment]
Ich kann heute nicht weil ich krank bin. Weiteres hab ich dir in einer Mail geschrieben.

**Comment by wimueller** [comment]
Ich bin einigermaßen wieder auf den Beinen also kann ich morgen kommen. Wie sieht es bei dir aus mit der Präsentation? Was soll ich noch übernehmen?

**Comment by wimueller** [comment]
hat sich erledigt habe gerade die Mails gelesen.

**Comment by wimueller** [comment]
hast du meine Mail bekommen? Ich schreib dir hier falls du nicht in deine Mails guckst

**Comment by gitAdrianK** [comment]
hab se bekommen, ausblick is okay, aber mit mp3 weiß ich nicht auf welchem legalen boden sich das befindet.

aussehen hab ich nochnichts gemacht, deswegen siehts scheiße aus, laptop werde ich mitbringen wo auch die gesammelten daten drin sind

**Comment by gitAdrianK** [comment]
Hab dir die überarbeitete version zugeschickt, kritik bitte
