### ISSUE TITLE
Splitting at "-" or "von" unreliable

### ISSUE THREAD

**Issue by gitAdrianK** [akrimpenfort/pir-radiostation-analyser#9]
Should "-" or "vor" be used other than dividing title and artist the split might not be correct.

- For NJOY and Antenne as soon as rust 1.15 comes serde can be used
- WDR needs some kind of other solution

**Comment by wimueller** [comment]
Which WDR Channel do you mean?

**Comment by gitAdrianK** [comment]
All of them, since they only provide a single line of text.
I'm tempted to only fix it for NJOY and NDR stations and close it with the tag "wontfix"

**Comment by gitAdrianK** [comment]
Naive attempt at fixing "-"-split by requiring spaces before and after.
